import 'package:hippocamp/models/posts-creation/attachment_types.dart';

// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'app_state_repository.freezed.dart';

@freezed
class AppState with _$AppState {
  const factory AppState({@Default([]) List<AttachmentType> attachmentTypes}) =
      _AppState;
}
