import 'package:hippocamp/models/responses/posts_response_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'post_repository.freezed.dart';

@freezed
class PostsRepository with _$PostsRepository {
  const factory PostsRepository({
    @Default([]) List<Post> allPosts,
    @Default([]) List<Post> selectedPosts,
    @Default([]) List<Post> filteredPosts,
  }) = _PostsRepository;
}
